# Generated by Django 4.2.25 on 2025-10-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NovaX_webpage', '0003_appreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('AI_COUNSELING', 'AI Career Counseling'), ('APTITUDE', 'Aptitude Test'), ('PERSONALITY', 'Personality Test'), ('EDUCATIONAL', 'Educational Test')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_data', models.JSONField(blank=True, default=dict)),
                ('predictions', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='NovaX_webpage.quizattempt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
